[general]
import = [
  "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[window]
opacity = 0.8
decorations = "full"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[font]
size = 10.0

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
thickness = 0.7

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/bash"

