[general]
import = [
  #"~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
  "~/.config/alacritty/themes/themes/dracula.toml"
  #"~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[window]
opacity = 0.5
decorations = "full"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[font]
size = 9.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.italic]
family = "DejaVu Sans Mono"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
thickness = 0.7

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/bash"

