[window]
opacity = 0.5
decorations = "full"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[font]
size = 9.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.italic]
family = "DejaVu Sans Mono"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
thickness = 0.7  # Alacritty uses 0.0–1.0 range, so 4.0/10 ~= 0.4

[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.cursor]
text = "#1a1a1a"
cursor = "#00ffcc"

[colors.normal]
black   = "#272822"
red     = "#f92672"
green   = "#a6e22e"
yellow  = "#f4bf75"
blue    = "#66d9ef"
magenta = "#ae81ff"
cyan    = "#38ccaa"
white   = "#f8f8f2"

[colors.bright]
black   = "#75715e"
red     = "#f92672"
green   = "#a6e22e"
yellow  = "#f4bf75"
blue    = "#66d9ef"
magenta = "#ae81ff"
cyan    = "#38ccaa"
white   = "#f9f8f5"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/bash"

