[general]

[window]
opacity = 0.75
decorations = "full"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[font]
size = 7

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
thickness = 0.7

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/bash"

[colors.primary]
background = "#080808"
foreground = "#dcdccc"

[colors.cursor]
text = "#0f1011"
cursor = "#dcdccc"

[colors.normal]
black   = "#1d1f21"
red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#f0c674"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#c5c8c6"

[colors.bright]
black   = "#666666"
red     = "#d54e53"
green   = "#b9ca4a"
yellow  = "#e7c547"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0ba"
white   = "#eaeaea"
